
name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
        aws-region: us-east-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push
      run: |
        docker build -t tech-news-scraper .
        docker tag tech-news-scraper:latest \
          123456789012.dkr.ecr.us-east-1.amazonaws.com/tech-news-scraper:latest
        docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/tech-news-scraper:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster tech-news-cluster \
          --service tech-news-service \
          --force-new-deployment